#Convert files to unix line endings
FROM perl as builder
ARG provider
COPY ./provider/${provider} /provider/${provider}
WORKDIR /provider/${provider}
RUN find $directory -type f -name "*.sh"  | xargs perl -pi -e 's/\r\n/\n/g'

#create container with terraform installed
FROM golang:alpine as terraformBase
ENV TERRAFORM_VERSION=0.10.0
RUN apk add --update git bash openssh make
ENV TF_DEV=true
ENV TF_RELEASE=true
WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/hashicorp/terraform.git ./ && \
    git checkout v${TERRAFORM_VERSION} && \
    /bin/bash scripts/build.sh
WORKDIR $GOPATH

#Build terraform provider dev environment
FROM terraformBase
ARG provider
ENV mode $mode \
	testPrefix $testPrefix \
	subscriptionId $subscriptionId \
	clientId $clientId \
	clientSecret $clientSecret \
	tenantId $tenantId \
	location $location \
	locationAlt $locationAlt
COPY --from=builder /provider/${provider} /go/src/github.com/terraform-providers/${provider}
WORKDIR /go/src/github.com/terraform-providers/${provider}
RUN make fmt
RUN make build
CMD export ARM_SUBSCRIPTION_ID=${subscriptionId}; \
	export ARM_CLIENT_ID=${clientId}; \
	export ARM_CLIENT_SECRET=${clientSecret}; \
	export ARM_TENANT_ID=${tenantId}; \
	export ARM_TEST_LOCATION=${location}; \
	export ARM_TEST_LOCATION_ALT=${locationAlt}; \
	if [ ${mode} = 'test' ]; then make test TESTARGS='-run=${testPrefix}'; \
    	elif [ ${mode} = 'testacc' ]; then make testacc TESTARGS='-run=${testPrefix}'; \
		else bash; \
	fi